# Generated by Django 2.1.5 on 2019-02-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='if_post',
            field=models.BooleanField(default=False),
        ),
    ]
