# Generated by Django 2.1.5 on 2019-02-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_if_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='origin_account',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='origin_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
