# Generated by Django 2.1.5 on 2019-02-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190209_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='origin_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
